DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS PATIENT_ADDRESS;

CREATE TABLE PATIENT (
  ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(4000) NOT NULL,
  LAST_NAME VARCHAR(4000) NOT NULL,
  AGE INT NOT NULL,
  SEX VARCHAR(100) NOT NULL,
  CONTACT_NUMBER VARCHAR(4000) DEFAULT NULL
);

CREATE TABLE PATIENT_ADDRESS (
   ID INT NOT NULL,
   ADDRESS_ID INT PRIMARY KEY,
   ADDRESS_LINE_1 VARCHAR(4000) DEFAULT NULL,
   ADDRESS_LINE_2 VARCHAR(4000) DEFAULT NULL,
   CITY VARCHAR(4000) DEFAULT NULL,
   COUNTRY VARCHAR(4000) NOT NULL,
   FOREIGN KEY (ID) REFERENCES PATIENT(ID) ON DELETE CASCADE
 );

INSERT INTO PATIENT (ID,FIRST_NAME,LAST_NAME,AGE,SEX,CONTACT_NUMBER) 
VALUES
(1,'Aliko', 'Dangote', 18,'Male','+65 96114239'),
(2,'Aliko John', 'Dangote', 24,'Female','+65 96114239'),
(3,'Aliko Tost', 'Dangote', 32,'Transgender','+65 96114239');

INSERT INTO PATIENT_ADDRESS (ID,ADDRESS_ID,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,COUNTRY) 
VALUES
(1,1,'03#03', 'Block 718','Tampiness','Singapore'),
(1,2,'03#04', 'Block 720','Simei','Singapore'),
(2,3,'45', 'Block Street 1','Blowlervare','France');

CREATE SEQUENCE PATIENT_SEQ
start with 4
increment by 1;

CREATE SEQUENCE PATIENT_ADDRESS_SEQ
start with 4
increment by 1;